name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        with:
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY_DEMEESTERDEV_GITHUB_IO }}
          publish_dir: ./public
          external_repository: demeesterdev/demeesterdev.github.io
          publish_branch: master
          user_name: github_actions
          user_email: github_actions@demeester.dev
          commit_message: publish from 